<a href="https://colab.research.google.com/github/DiogoBernardoPT/LearningWay/blob/main/Modulo_1_Clase_1_Repaso_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Repaso Clases HackABoss - Target: 3 meses repaso diarios con ejercicios

## Operadores Aritmeticos

%
Modulo
x % y

El módulo (representado por el operador % en muchos lenguajes de programación) se usa precisamente para obtener el resto de una división entre dos números. Es útil para determinar si un número es par o impar, entre otras cosas.



In [ ]:
number = 7

# Usamos el operador modulo (%) para obtener el residuo de la división
if number % 2 == 0:
    print(f"{number} es par.")
else:
    print(f"{number} es impar.")


7 es impar.


In [ ]:
number = 6

# Usamos el operador modulo (%) para obtener el residuo de la división
if number % 2 == 0:
    print(f"{number} es par.")
else:
    print(f"{number} es impar.")

6 es par.


In [ ]:
10 **2

100

 Built-in Methods
Las cadenas de caractéres tienen una gran variedad de métodos, estos son algunos de los más utilizados:

.capitalize()
.isalnum()

.title()
.isalpha()

.casefold()
.isascii()

.center()
.isdecimal()

.count()
.isdigit()

.split()
.isidentifier()

.startswith()
.islower()

.endswith()
.isnumeric()

.find()
.isspace()

.index()
.istitle()

.format()
.isupper()

.upper()
.lower()

.replace()
.swapcase()

.strip()
.join()

Vídeo del martes 28 de mayo, 2024 desde las 17:54 a las 21:10

Duda de Sandra - 02:36:16 - Puede salir en una pregunta de entrevista: Lista dentro de tuplas.

Reflexion de Gabri sobre niveles de los items de las tuplas  - 02:44:10

# Reverse de tuplas: [::-1] - Revierte la orden de la lista.

## 2:55:50 - Diferencias entre extend y append.

In [ ]:
lista_ejemplo = []

lista_ejemplo.extend([1, 2, 3])

print(lista_ejemplo)
len(lista_ejemplo)

[1, 2, 3]


3

In [ ]:
lista_ejemplo = [1, 2, 3]
lista_ejemplo.append([1, 2, 3])

print(lista_ejemplo)
len(lista_ejemplo)

[1, 2, 3, [1, 2, 3]]


4

extend([1, 2, 3]): El método extend() agrega todos los elementos de la lista [1, 2, 3] individualmente a la lista original. Es decir, "extiende" la lista lista_ejemplo añadiendo cada elemento de la lista proporcionada como un nuevo elemento de la lista original.

En este caso, lista_ejemplo pasa de ser una lista vacía [] a contener los elementos [1, 2, 3].
Resultado: lista_ejemplo es ahora [1, 2, 3] y su longitud es 3.



append([1, 2, 3]): El método append() agrega el entero [1, 2, 3] como un único elemento dentro de la lista. No extiende los elementos, sino que agrega la lista completa como un solo elemento dentro de la lista original.

En este caso, lista_ejemplo comienza como [1, 2, 3], y luego se le agrega una nueva lista [1, 2, 3] como un único elemento. Es decir, la lista se convierte en [1, 2, 3, [1, 2, 3]].
Resultado: lista_ejemplo es ahora [1, 2, 3, [1, 2, 3]] y su longitud es 4. La longitud se incrementa porque el método append() añade un solo elemento (que es una lista) y no los elementos de esa lista individualmente.

Resumen de la diferencia:

extend(): Añade cada elemento de la lista proporcionada de manera individual a la lista original.

append(): Añade la lista completa como un único elemento dentro de la lista original.

## Bucle for y While

Vídeo del martes 28 de mayo, 2024 desde las 21:10 a las 21:53

15:00 - Inicio de los Bucles

### Hacer apuntes despues, con ayuda de la siguiente clase + descripciones de GPT




In [1]:
lista = [2, 4 ,8]

contador = 0

for num in lista:
  print(num)
  contador = contador + 1

for num2 in lista:
  contador = contador + 1



2
4
8


In [3]:
print(contador)

6


En este primer código, tienes una lista con tres elementos: [2, 4, 8].
El primer bucle for recorre cada elemento de la lista y, por cada iteración, imprime el número y aumenta el contador en 1.
Al final de este bucle, el contador se incrementa 3 veces, ya que hay 3 elementos en la lista (el contador pasa a ser 3).
Luego, en el segundo bucle for, recorres nuevamente la lista y por cada elemento, aumentas el contador en 1.
En total, el contador se incrementa otras 3 veces, y su valor final es 6.

2N

In [4]:
lista = [2, 4 ,8]

contador = 0

for num in lista:
  for num2 in lista:
    contador = contador + 1

In [5]:
print(contador)

9


En este segundo código, también tienes una lista de 3 elementos.
El primer bucle for recorre los elementos de la lista (3 elementos), pero dentro de este bucle hay otro bucle for anidado que también recorre toda la lista (otros 3 elementos).
En total, cada vez que el primer bucle recorre un elemento, el segundo bucle realiza 3 iteraciones más (una por cada elemento de la lista).
Por lo tanto, el contador se incrementa 9 veces (3 elementos en el primer bucle * 3 elementos en el segundo bucle).

N²

In [6]:
# Ejercicio de clase

nombres = ['Maria', 'Jose', 'Ricardo', 'Federico']
# Se define como nombre largo, aquellos que tengan seis o mas caracteres.
# Generar una nueva lista de nombres largos, donde queden los nombres que sean largos

In [7]:
lista = []

for nombre in nombres:
  if len(nombre) >= 6:
    lista.append(nombre)

In [8]:
lista

['Ricardo', 'Federico']

In [ ]:
# Source: Vídeo del jueves 30 de mayo, 2024 desde las 17:49 a las 20:55 - 1:40:42

In [ ]:
# Inicio y final de un ciclo de if - if elif else - if elif if - 1:50

In [1]:
#Ejercicio

numeros = input('Ingresa una lista de numeros separados por espacios: ')
numeros

Ingresa una lista de numeros separados por espacios: 1 2 3 4 5


'1 2 3 4 5'

In [3]:
numeros = numeros.split(' ')
numeros

['1', '2', '3', '4', '5']

In [4]:
numeros_int = []

for numero in numeros:
  numeros_int.append(int(numero))

In [5]:
numeros_int

[1, 2, 3, 4, 5]

# Zip y Enumerate

Esta función toma como argumento objetos iterables para recorrerlos al mismo tiempo en un bucle.

#### Vídeo del jueves 30 de mayo, 2024 desde las 20:55 a las 21:40 - 30:00

In [13]:
lista_1 = ['a', 'b', 'c', 'd', 'e']
lista_2 = [1, 2, 3, 4, 5]

for i in range(len(lista_2)):
  print(lista_1[i],lista_2[i])



a 1
b 2
c 3
d 4
e 5


In [14]:
# Lo mismo con zip

lista_1 = ["a", "b", "c", "d", "e"]
lista_2 = [1,    2,    3,   4,   5,  6 , 7]

for i,j in zip(lista_1, lista_2):
  print(i,j)

a 1
b 2
c 3
d 4
e 5


#### zip(lista_1, lista_2) emparejará las primeras 5 tuplas, tomando un elemento de cada lista en cada iteración, y luego dejará de generar más tuplas cuando se agoten los elementos de lista_1, aunque lista_2 tenga elementos restantes.

En tu caso, lista_1 tiene 5 elementos y lista_2 tiene 7. Como zip() se detiene cuando llega al final del iterable más corto, se detendrá después del quinto elemento, ya que esa es la longitud de lista_1.

In [ ]:
zip? # Mirar documentacion


## Enumerate

Esta función "crea" un índice utilizando un objeto iterable, se usa en conjunto con los bucles para tener un tipo de "contador". - 41:00

In [17]:
lista = ["a", "b", "c", "d", "e"]

In [18]:
for idx, letra in enumerate(lista):
  print(idx, letra)

0 a
1 b
2 c
3 d
4 e


### Sets

 Sets (set)
En python, un set es una colección de elementos que no posee órden, por lo tanto no tiene indice. Debido a esto no podemos elegir en que orden aparecen sus elementos.
Los sets son mutables y NO permiten elemento repetidos, lo que es útil en situaciones que tenemos que utilizar valores únicos.
Se denotan con llaves {} y son muy utilizados en la teoria de grupos.

Métodos

.add() - Agrega un elemento al set

.clear() - Vacia el set

.difference() - Retorna los elementos no comunes de ambos sets

.remove() - Elimina un elemento especifico del set

.pop() - Elimina un elemento del set y lo retorna

.intersection() - Retorna los elementos en comun de dos sets

.union() - Retorna la unión de dos sets

.update() - Agrega a un set los elementos de otro objeto iterable

29:00


### Ejemplos prácticos donde es más adecuado usar un set en vez de un diccionario:

1. Eliminación de duplicados

El uso más común de un set es para eliminar duplicados de una lista o colección de elementos. Los sets no permiten elementos duplicados, por lo que si necesitas garantizar que todos los elementos sean únicos, un set es ideal.

In [19]:
nombres = ["Ana", "Carlos", "Ana", "Juan", "Carlos", "Pedro"]
nombres_unicos = set(nombres)

print(nombres_unicos)

{'Juan', 'Carlos', 'Ana', 'Pedro'}


Operaciones matemáticas con conjuntos
Los sets son ideales cuando necesitas realizar operaciones típicas de teoría de conjuntos, como la unión, intersección, diferencia, y diferencia simétrica.

Ejemplo:
Supón que tienes dos conjuntos de estudiantes que tomaron diferentes cursos, y deseas encontrar los estudiantes que tomaron ambos cursos (intersección), o los que tomaron al menos uno de los dos cursos (unión).

In [20]:
curso_1 = {"Ana", "Carlos", "Juan", "Pedro"}
curso_2 = {"Carlos", "Pedro", "Luis", "María"}

# Intersección (quienes están en ambos cursos)
interseccion = curso_1 & curso_2
print(interseccion)

# Unión (quienes están en al menos uno de los dos cursos)
union = curso_1 | curso_2
print(union)

{'Pedro', 'Carlos'}
{'María', 'Pedro', 'Carlos', 'Juan', 'Luis', 'Ana'}


##### Aunque podrías usar un diccionario con las claves representando a los estudiantes, un set es mucho más directo y eficiente para este tipo de operaciones.

3. Evitar almacenar valores adicionales
Los sets solo contienen valores, mientras que los diccionarios almacenan claves y valores.

Si solo necesitas una colección de elementos y no necesitas asociar información adicional con esos elementos, un set es más adecuado porque ocupa menos espacio y es más sencillo de manejar.

## Conclusión:
Usar un set es más apropiado cuando:

Necesitas únicos elementos.

Quieres realizar operaciones de conjunto (unión, intersección, diferencia).

Necesitas comprobar si un elemento existe sin asociarle un valor.

No te importa almacenar solo los elementos, sin valores adicionales.

Un diccionario es mejor cuando necesitas asociar clave-valor, pero si solo necesitas almacenar los elementos de forma única sin valores adicionales, un set es mucho más adecuado y eficiente.

In [ ]:
# Hacer ejercicios de Sets



 Ejercicio 11

1. Pide al usuario que ingrese 3 empresas de tecnología, estos elementos agregalos al set_1 = {"Meta", "Google", "Amazon"}

2. Verifica que no se repita ninguna empresa y dile al usuario que no se repitio ninguna empresa.

In [25]:
set_1 = {"Meta", "Google", "Amazon"}

In [26]:
companies = str(input('Please input 3 companies separated by commas: '))
companies = companies.split(',')
print(companies)

Please input 3 companies separated by commas: Transperfect,Airbnb,Telus
['Transperfect', 'Airbnb', 'Telus']


In [27]:
set_1.update(companies)
set_1

{'Airbnb', 'Amazon', 'Google', 'Meta', 'Telus', 'Transperfect'}

In [29]:
if len(set_1) == 6:
  print('None of the companies repeats')

else:
  print('There are companies that repeat')

None of the companies repeats


Ejercicio 12

1 . Repite el ejercicio anterior pero ahora imprime las empresas que se repiten en caso de que existiera uno o más que se repitan.

In [6]:
set_1 = {"Meta", "Google", "Amazon"}

set_2 = str(input('Please input 3 companies separated by commas: '))

set_2 = [empresa.strip() for empresa in set_2.split(',')]

print(set_2)

Please input 3 companies separated by commas: Amazon,Global,Google
['Amazon', 'Global', 'Google']


In [7]:
for empresa in set_2:
  if empresa in set_1:
    print('This company repeats: ', empresa)

  else:
    set_1.update([empresa])

print(set_1)

This company repeats:  Amazon
This company repeats:  Google
{'Amazon', 'Global', 'Meta', 'Google'}


Ejercicio 13

1. Dadas las siguientes frases_1 = "En una galaxia lejana" y frase_2 = "Una galaxia llamadá Via Lactea", haz la intersección de las palabras.

In [11]:
phrase_1 = "En una galaxia lejana"
phrase_2 = "Una galaxia llamadá Via Lactea"

set_1 = set(phrase_1.split())
set_2 = set(phrase_2.split())

print(set_1)
print(set_2)


{'En', 'una', 'lejana', 'galaxia'}
{'Una', 'galaxia', 'Via', 'llamadá', 'Lactea'}


In [ ]:
intersect = phrase_1.interseccion(phrase_2)
intersect

Ejercicio 14

1. Encuentra la diferencia entre el set_1 = {9, 8, 7, 6, 5, 4, 3, 2} y el set_2 = {9, 8, 10}
2. Extra: hazlo utilizando un bucle for y no la función.

In [12]:
set_1 = {9, 8, 7, 6, 5, 4, 3, 2}
set_2 = {9, 8, 10}

lista = []

for numeros in set_1:
  if numeros not in set_2:
    lista.append(numeros)

print(lista)


[2, 3, 4, 5, 6, 7]


## Dictionaries (dict)
En python, los diccionarios son una estructura de datos y un tipo de dato. La principal característica de los diccionarios es que cada elemento tiene un par de llave y valor (key y value).

La llave o key se utiliza para identificar un elemento del diccionario, funciona como un indice, normalmente las llaves son numeros o strings.

El valor o value es el elemento asociado a la llave, este valor puede ser cualquier tipo de dato (numero, string, lista, tupla, diccionario...).

Al igual que los sets los diccionarios NO tienen un orden, además las llaves son únicas, es decir, no se pueden repetir.

Los diccionarios se denotan con {} y utilizan : para separar las llaves y los valores. Este tipo de dato también se le conoce como JSON en otros lenguajes.

Vídeo del lunes 3 de junio, 2024 desde las 17:41 a las 21:27 - 52:00

 Ejercicio 15

1. Crea un diccionario con 5 elementos (5 llaves y 5 valores)

Llave: Color

Valor: Numero de letras del color

In [ ]:
dict = {yellow : 1, red : 2, green : 3, brown : 4, purple : 5}

 Ejercicio 16

1. Crea un diccionario con 5 elementos pero esta vez pregunta el usuario por cada llave y valor.

Llave: Color

Valor: Numero de letras del color

In [13]:
dict_empty = {}

for i in range(5): # Vamos a repetir el proceso 5 veces
  key = str(input('Input one color: ')) # Pedimos al usuario un color (que será la "llave")
  value = len(key) # Calculamos el número de letras del color (será el "valor")

  dict_empty[key] = value # Añadimos la clave y el valor al diccionario





Input one color: Yellow
Input one color: Red
Input one color: Purple
Input one color: Green
Input one color: Brown


In [14]:
dict_empty

{'Yellow': 6, 'Red': 3, 'Purple': 6, 'Green': 5, 'Brown': 5}

# Notas de repaso

[] se usa para acceder a los valores del diccionario a través de las claves. Los corchetes nos permiten obtener, agregar o modificar el valor asociado a una clave específica en un diccionario.

-------------------------------------------------

Comparando dict['clave'] y dict.get('clave'):
1. Acceso con dict['clave']:
Sintaxis: valor = dict['clave']

Comportamiento:

Si la clave existe en el diccionario, devuelve el valor asociado con esa clave.

Si la clave no existe, genera un error de tipo KeyError.
-------------------------------------------------

Acceso con dict.get('clave'):
Sintaxis: valor = dict.get('clave')

Comportamiento:

Si la clave existe, devuelve el valor asociado con esa clave, igual que dict['clave'].
Si la clave no existe, no lanza un error. En lugar de eso, devuelve None por defecto. Sin embargo, puedes especificar un valor predeterminado que se devuelve en caso de que la clave no se encuentre.



 Ejercicio 17

1. Repite el ejercicio anterior pero de la siguiente forma:

Primero crea en una lista los colores y en otra lista el numero de letras.

Después crea el diccionario a partir de las listas.

In [16]:
colors = ['Yellow','Brown',
          'Red','Purple', 'Blue']

nr_letters = [6, 5, 3, 6, 4]

dict_empty = {}

for color, count in zip(colors,nr_letters):
  print(color,count)
  dict_empty[color] = count

dict_empty

Yellow 6
Brown 5
Red 3
Purple 6
Blue 4


{'Yellow': 6, 'Brown': 5, 'Red': 3, 'Purple': 6, 'Blue': 4}

 Ejercicio 18

Pide al usuario que ingrese 3 números distintos y guarda esos números como llaves y crea los valores utilizando la siguiente formula:

x : x**2

Donde x es la llave.

In [17]:
dict_empty = {}

for i in range(3):
  number = int(input('Please, input an integer number: '))
  dict_empty[number] = number **2

dict_empty




Please, input an integer number: 2
Please, input an integer number: 6
Please, input an integer number: 10


{2: 4, 6: 36, 10: 100}

Explicación paso a paso:
dict_vacio = {}: Creamos un diccionario vacío donde almacenaremos las claves y sus valores.

for i in range(3):: Este bucle for se ejecutará 3 veces (una vez por cada número que el usuario ingrese).

range(3) genera los números 0, 1, 2, pero no los usamos directamente. Lo importante es que el bucle se repita 3 veces.
numero = int(input("Ingrese un número entero: ")): En cada iteración del bucle, le pedimos al usuario que ingrese un número. Este número se convierte en un entero gracias a int().

dict_vacio[numero] = numero**2: Usamos el número ingresado como clave y su cuadrado como valor. Esto agrega un nuevo par clave-valor al diccionario.

print(dict_vacio): Finalmente, mostramos el diccionario completo con las claves y sus respectivos valores (cuadrados de los números).

Resumiendo la pregunta del input() y el bucle:
Si necesitas que el programa repita una acción varias veces (en este caso, pedir números al usuario), el input() debe estar dentro del bucle.


Usamos range(3) para que el bucle se ejecute 3 veces. Podrías usar otro número si necesitaras pedir más o menos números.

Resumen de las salidas más comunes:

Método	    Tipo de salida
-------------------------------------------------

str.upper()	String (cadena)

str.split()	Lista (list)

str.strip()	String (cadena)

list.append()	None (modifica lista)

list.pop()	Elemento (valor)

dict.items()	dict_items (view object, iterable de tuplas)

dict.keys()	dict_keys (view object, iterable de claves)

dict.values()	dict_values (view object, iterable de valores)

dict.get()	Valor (o None si no existe)

set.add()	None (modifica set)

set.union()	Set (nuevo set)

range()	range object (iterable, pero no lista ni tupla)

 Ejercicio 19

Pide al usuario que ingrese una frase y agrega las palabras como keys y la frecuencia de cada palabra como value en un diccionario.

Usa la función Counter.

In [20]:
phrase = str(input('Please, write a sentence you wish: '))

phrase = phrase.split(' ')

phrase

Please, write a sentence you wish: o benfica e o maior


['o', 'benfica', 'e', 'o', 'maior']

In [21]:
from collections import Counter
Counter(phrase)

Counter({'o': 2, 'benfica': 1, 'e': 1, 'maior': 1})

 Ejercicio 20

Crea un programa donde las keys son 7 números aleatorios entre el 100 y el 200 y en los values debe de estar la palabra par o impar, si el número es par o impar

In [22]:
import random
dict_empty = {}

for i in range(7):
  random_num = random.randint(100,200)

  if random_num % 2 == 0:
    dict_empty[random_num] = 'Even'

  else:
    dict_empty[random_num] = 'Odd'

dict_empty





{123: 'Odd',
 185: 'Odd',
 124: 'Even',
 101: 'Odd',
 131: 'Odd',
 125: 'Odd',
 150: 'Even'}

 Ejercicio 21

Crea un programa donde las keys son 10 números enteros aleatorios entre el 1 y el 50 y para cada value del diccionario vamos a utilizar la siguiente formula x : 1/x

In [23]:
dict_empty = {}

for i in range(10):
  random_num = random.randint(1, 50)

  dict_empty[random_num] = 1/random_num

dict_empty

{16: 0.0625,
 43: 0.023255813953488372,
 14: 0.07142857142857142,
 30: 0.03333333333333333,
 19: 0.05263157894736842,
 3: 0.3333333333333333,
 23: 0.043478260869565216,
 9: 0.1111111111111111,
 8: 0.125}

 Ejercicio 22

Crea un programa que dados los siguientes diccionarios: d1 = {"a" : 125, "b" : 130, "c" : 150}, d2 = {"e" :  10, "b" : 20, "a" : 30}, sume los items que tienen la misma key y guarde esas keys con la suma de los values en un nuevo diccionario

In [26]:
d1 = {"a" : 125, "b" : 130, "c" : 150}
d2 = {"e" : 10, "b" : 20, "a" : 30}

In [28]:
d3 = {}

d3.update(d1)

for k, v in d2.items():
  if k in d3:
    d3[k] += v
  else:
    d3[k] = v

d3


{'a': 155, 'b': 150, 'c': 150, 'e': 10}

### Extra:

lista_nombres = ['Federico', 'maria','JUAN','Ricardo']

### Generar un dicc donde la clave sea el nombre
### Y el valor la cantidad de caracteres
### El nombre debe estar primera letra mayuscula y las demas minusculas

## Ejemplo:
{'Federico': 8, 'Maria' : 5, 'Juan': 4, 'Ricardo':7}



In [33]:
lista_nombres = ['Federico', 'maria','JUAN','Ricardo']

dict_empty = {}

for nombre in lista_nombres:
  print(nombre.capitalize())
  dict_empty[nombre.capitalize()] = len(nombre)

dict_empty




Federico
Maria
Juan
Ricardo


{'Federico': 8, 'Maria': 5, 'Juan': 4, 'Ricardo': 7}

for nombre in lista_nombres.capitalize():
  print(nombre)
El error ocurre porque lista_nombres es una lista, y capitalize() es un método de cadenas de texto (strings), no de listas.

Es decir, el método capitalize() solo se puede aplicar a cadenas de texto individuales (strings), pero no a listas completas.

Por lo tanto, cuando intentas hacer lista_nombres.capitalize(), Python te dice que no puede encontrar el método capitalize porque no existe para listas.

-------------------------------------------------


Por qué funciona en el segundo ejemplo?

for nombre in lista_nombres:
  print(nombre.capitalize())


En este caso, el iterable sobre el que haces el bucle for es lista_nombres, que es una lista de cadenas de texto (strings).

Entonces, en cada iteración, la variable nombre toma el valor de un string individual de la lista. Y como nombre es un string (por ejemplo 'maria', 'JUAN', etc.), puedes aplicar el método capitalize() a esa cadena de texto específica, lo cual es válido.

Vídeo del lunes 3 de junio, 2024 desde las 17:41 a las 21:27

1:37:59

### Extra 2

Tendre una variable, objetivo, por ejemplo igual a 4
objetivo = 4

Y quiero ver que nombre/s tienen esa cantidad de caracteres.

Para reflexionar. ¿Cómo guardo el/los nombres resultantes?
¿Cómo los obtengo(tip iterar con .items() )?


longitudes = {'Federico': 8, 'Maria': 5, 'Juan': 4, 'Ricardo': 7, 'John': 4}

In [35]:
length = {'Federico': 8, 'Maria': 5, 'Juan': 4, 'Ricardo': 7, 'John': 4}
length

{'Federico': 8, 'Maria': 5, 'Juan': 4, 'Ricardo': 7, 'John': 4}

In [36]:
target = 4

names_found = []

for name,n_char in length.items():
  if n_char == target:
    names_found.append(name)
names_found



['Juan', 'John']

Way of thinking:
1. Inicializar el diccionario length con los nombres y sus longitudes.

2. Tener un target que define cuántos caracteres deseas que tenga el nombre.

3. Usar un bucle for para recorrer cada clave (nombre) y su valor (longitud).

Si la longitud coincide con el target, agregas ese nombre a la lista names_found.

Vídeo del lunes 3 de junio, 2024 desde las 17:41 a las 21:27 - 1:42:00

In [ ]:
# Quede en los diccionarios anidados 2:21:48


## Diccionarios anidados

Cuando tenemos un diccionario anidado, para poder acceder a los elementos de los diccionarios más internos debemos ir entrando en cada llave hasta llegar al elemento que queramos



In [1]:
dict_2 = {1 : {"nombre" : "pablo", "apellido" : "rodriguez"},
          2 : {"nombre" : "juan", "apellido" : "perez"}}

dict_2

{1: {'nombre': 'pablo', 'apellido': 'rodriguez'},
 2: {'nombre': 'juan', 'apellido': 'perez'}}

In [2]:
# Ejemplo

dict_2[1]



{'nombre': 'pablo', 'apellido': 'rodriguez'}

In [3]:
dict_2[1]["nombre"]

'pablo'

In [4]:
dict_2.get(1).get("nombre")

'pablo'

In [5]:
dict_2[1]["apellido"]

'rodriguez'

In [6]:
dict_2[2]

{'nombre': 'juan', 'apellido': 'perez'}

In [7]:
 dict_2[2]["nombre"]

'juan'

# Diccionarios anidados Ejercicio clase

dict_2 = {"123L" : {"nombre" : "pablo", "apellido" : "rodriguez", "tel": 5},
          "222L" : {"nombre" : "juan", "apellido" : "perez", "tel": 4},
          "2340L" : {"nombre" : "miguel", "apellido" : "sanchez"}}

dict_2
1. voy a recorrer el diccionario.
2.  si detecto que alguien no tieen número de teléfono, le agrego uno por defecto
3. que será el 444.

In [1]:
dict_2 = {"123L" : {"nombre" : "pablo", "apellido" : "rodriguez", "tel": 5}, "222L" : {"nombre" : "juan", "apellido" : "perez", "tel": 4}, "2340L" : {"nombre" : "miguel", "apellido" : "sanchez"}}

dict_2

{'123L': {'nombre': 'pablo', 'apellido': 'rodriguez', 'tel': 5},
 '222L': {'nombre': 'juan', 'apellido': 'perez', 'tel': 4},
 '2340L': {'nombre': 'miguel', 'apellido': 'sanchez'}}

In [4]:
for k, v in dict_2.items():
  if 'tel' not in v:
    v['tel'] = 444

print(dict_2)

# Aprender a poner las variables con nombres que tengan mas sentido

# Ejemplo:
#  for dni, info in dict_2.items():
   # if "tel" not in info:
       # dict_2[dni]["tel"] = 444


{'123L': {'nombre': 'pablo', 'apellido': 'rodriguez', 'tel': 5}, '222L': {'nombre': 'juan', 'apellido': 'perez', 'tel': 4}, '2340L': {'nombre': 'miguel', 'apellido': 'sanchez', 'tel': 444}}


Resumen de lo aprendido:

Recorrer un diccionario anidado: Usamos dict_2.items() para obtener tanto las claves como los valores de un diccionario. Luego, accedemos al diccionario interno para hacer las comprobaciones necesarias.

Verificación de claves en diccionarios: Se puede verificar si una clave está presente en un diccionario con 'clave' not in diccionario.

Modificar un diccionario anidado: Accedemos a las claves y valores dentro de los diccionarios internos utilizando value['clave'].

In [ ]:
# Codigo aun mas seguro, en los casos mas complejos que tengamos que acceder con mas detalle

for dni, info in dict_2.items():
  if 'tel' not in info:
    dict_2[dni]["tel"] = 444

# Esto funcionaria mejor, ya que ni siempre va a funcionar con el ejemplo de arriba( principalmente con mucho mas datos)

 Existe una función que nos ayuda a contar el número de elementos de un objeto, la función retorna un objeto parecido a los diccionarios.

 from collections import Counter

In [6]:
from collections import Counter

string = "aaaabbbbcccccddddddeeeeeeeffffffffffgggggggggggggggghhhhhhhhhhhhhhhhhhhhhh"
print(string)

Counter(string)



aaaabbbbcccccddddddeeeeeeeffffffffffgggggggggggggggghhhhhhhhhhhhhhhhhhhhhh


Counter({'a': 4, 'b': 4, 'c': 5, 'd': 6, 'e': 7, 'f': 10, 'g': 16, 'h': 22})

# Funciones

Una función es un bloque de código con un nombre asociado, que recibe cero o más argumentos como entrada, sigue una secuencia de sentencias, la cuales ejecuta una operación deseada y devuelve un valor y/o realiza una tarea.En python las funciones se definen con la palabra reservada def y si es necesario, se utiliza la palabra reservada return.


Vídeo del lunes 3 de junio, 2024 desde las 17:41 a las 21:27 - 3:05



In [ ]:
# Duda 3:19

In [7]:
# Función que retorna el cuadrado de un número si es par.

def func_cuadrado_par(x = 100):
    if x % 2 == 0:
        return x**2
    else:
        return x

In [8]:
# Función que retorna el cuadrado de un número si es par.

def func_cuadrado_par(x = 100):
    if x % 2 == 0:
        return x**2
    return x

In [9]:
 func_cuadrado_par(10)

100

In [10]:
 func_cuadrado_par(7)

7

In [11]:
 func_cuadrado_par()

10000

In [12]:
# Mucha gente comete este error:

def ejemplo(lista):
  for numero in lista:
    numero = numero *2
    return numero

In [13]:
ejemplo([10, 5 , 10])

20

Explicación paso a paso:
La función ejemplo recibe una lista de números: [10, 5, 10].

El primer número en la lista es 10:

El número 10 se multiplica por 2, lo que da 20.
Se ejecuta return numero:

El return dentro del bucle hace que la función termine y devuelva el valor de numero (20) inmediatamente.
Como resultado, la función devuelve solo 20 y no sigue iterando sobre el resto de los elementos de la lista.

In [ ]:
"""
Quiero una función que tome una lista.
Y devuelva una nueva lista que contenga todos los elementos repetidos.

Entrada = [1,1,2,3,4,5,4,1,1,1]

Salida = [1,4]

Ayuda: Ayudate de una nueva lista
"""

In [14]:
def eliminate_duplicates(input_list):
  duplicates = []

  for element in input_list:
    if input_list.count(element) > 1 and element not in duplicates:
      duplicates.append(element)
  return duplicates



In [15]:
new_list = [1,1,2,3,4,5,4,1,1,1]
duplicates = eliminate_duplicates(new_list)

duplicates



[1, 4]

## Resumen:

.count() es un método disponible para listas en Python y permite contar cuántas veces aparece un valor específico dentro de la lista.

## Retornar más de un elemento

Hasta ahora hemos hecho funciones que solo retornan un elemento, número, lista... Pero podemos hacer que el return nos retorne varias elementos, de esta forma podemos asignar varias variables al mismo tiempo.

In [17]:
# Funcion que retorna el minimo y el maximo de una lista

def min_max_lista(lista):

    minimo = min(lista)
    maximo = max(lista)

    return minimo, maximo



In [18]:
lista = [1,1,2,3,4,5,4,1,1,1]

min_lista, max_lista = min_max_lista(lista)

min_lista, max_lista

(1, 5)

## Variables locales y globales

En Python las variables locales son aquellas definidas dentro de una función. Solamente son accesibles desde la propia función y dejan de existir cuando esta termina su ejecución.

Los parámetros de una función también son considerados como variables locales.En Python las variables globales son aquellas definidas en el cuerpo principal del programa fuera de cualquier función.

Son accesibles desde cualquier punto del programa, incluso desde dentro de funciones. También se puede acceder a las variables globales de otros programas o módulos importados.

Ver notebook 08.funciones

###  Estudiar variables locales y globales, con funciones





Vídeo del martes 4 de junio, 2024 desde las 17:46 a las 21:22 - 23:00


## Lambda (función anónima)
Python cuenta con la función lambda, también llamada función anónima, su utilidad es poder crear funciones sin tener que darle un nombre. Debido a la sintaxis de la función lambda está es un poco limitada.Se usa principalmente para funciones cortas, puede tomar muchos parámetros y puede retornar cualquier tipo de dato (numero, tupla, lista, diccionario...).

### Sintaxis básica de una función lambda:

lambda argumentos: expresión


Vídeo del martes 4 de junio, 2024 desde las 17:46 a las 21:22 - 25:00

In [19]:
string = "hola"

def contador_a(string):
    return string.lower().count("a")

contador_a('hola')

1

In [20]:
contador_a = lambda string : string.lower().count('a')

contador_a('Holaaaa')

4

In [ ]:
# Logica de pensamiento
def sumar_numeros(a, b):
    return a + b


# Lambda
sumar_numeros = lambda a, b: a + b

nombre de la funcion = variable

argumentos = lo que vamos a llamar en la funcion(a,b)

expresión a + b = return

Ordenación personalizada (sorted(), sort()):

Puedes usar una función lambda para especificar la clave de ordenación (key) cuando usas las funciones sorted() o sort().

In [ ]:
palabras = ["manzana", "banana", "kiwi", "cereza"]
palabras_ordenadas = sorted(palabras, key=lambda x: len(x))
print(palabras_ordenadas)  # Salida: ['kiwi', 'cereza', 'banana', 'manzana']

## Object-Oriented Programming (OOP)

Vídeo del martes 4 de junio, 2024 desde las 17:46 a las 21:22 - 01:13:00

# Mirar el notebook 10 - Modulo 1 para tener ejemplos visuales


La idea de la programación orientada a objetos puede parecer abstracta y compleja, pero ya hemos estado utilizando objetos sin darnos cuenta. Casi todo en Python es un objeto, todas las cadenas, listas, y diccionarios que hemos visto hasta ahora y que hemos usado han sido objetos.


### Objeto
El objeto es el centro de la programación orientada a objetos. Un objeto es algo que se visualiza, se utiliza y que juega un papel o un rol en el dominio del problema del programa. La estructura interna y el comportamiento de un objeto, en consecuencia, no es prioritario durante el modelado del problema.


### Clase
En el mundo real existen varios objetos de un mismo tipo o clase, por lo que una clase equivale a la generalización de un tipo específico de objetos. Una clase es una plantilla que define las variables y los métodos que son comunes para todos los objetos de un cierto tipo.

### Instancia
Una vez definida la clase se pueden crear objetos a partir de ésta, a este proceso se le conoce como crear instancias de una clase o instanciar una clase. En este momento el sistema reserva suficiente memoria para el objeto con todos sus atributos.Una instancia es un elemento de una clase (un objeto). Cada uno de los objetos o instancias tiene su propia copia de las variables definidas en la clase de la cual son instanciados y comparten la misma implementación de los métodos. Sin embargo, cada objeto asigna valores a sus atributos y es totalmente independiente de los demás.

### Método
Los métodos especifican el comportamiento de la clase y sus instancias. En el momento de la declaración hay que indicar cuál es el tipo del parámetro que devolverá el método.

### Atributos
Tipos de datos asociados a un objeto (o a una clase de objetos), que hace los datos visibles desde fuera del objeto y esto se define como sus características predeterminadas, cuyo valor puede ser alterado por la ejecución de algún método.




## Ejemplo practico

1. Clase (Plantilla)
La clase es como una plantilla o plano para crear objetos. En este caso, la clase sería "Perro". Esta clase define qué atributos (como nombre, edad y raza) tendrá cada perro, así como qué métodos (acciones que el perro puede hacer) podrá ejecutar, como ladrar o comer.



In [ ]:
class Perro:
    # Atributos (características)
    def __init__(self, nombre, edad, raza):
        self.nombre = nombre  # Atributo: Nombre del perro
        self.edad = edad      # Atributo: Edad del perro
        self.raza = raza      # Atributo: Raza del perro

    # Métodos (acciones que el perro puede hacer)
    def ladrar(self):
        print(f"{self.nombre} está ladrando!")

    def comer(self, comida):
        print(f"{self.nombre} está comiendo {comida}.")

2. Objeto (Instancia de la clase)
Una vez que tenemos la clase Perro, podemos crear objetos a partir de esa clase, que serían instancias de la clase.

En este caso, vamos a crear dos perros específicos.

In [ ]:
# Creamos dos instancias de la clase "Perro"
perro1 = Perro("Rex", 3, "Labrador")
perro2 = Perro("Bella", 5, "Beagle")

perro1 es una instancia de la clase Perro, donde el nombre es "Rex", la edad es 3 y la raza es "Labrador".

perro2 es otra instancia de la clase Perro, con nombre "Bella", edad 5 y raza "Beagle".

3. Métodos
Cada objeto tiene métodos definidos por la clase. Estos métodos nos permiten interactuar con el objeto.

Por ejemplo, el método ladrar() permite que el perro "ladre" y el método comer() permite que el perro coma algo.

In [ ]:
# Usamos los métodos
perro1.ladrar()  # Imprime: Rex está ladrando!
perro2.comer("carne")  # Imprime: Bella está comiendo carne.

4. Atributos
Los atributos de una clase son variables que almacenan la información sobre cada objeto.

En este caso, cada perro tiene atributos como nombre, edad y raza. Esas características son específicas de cada instancia.

In [ ]:
# Accedemos a los atributos
print(perro1.nombre)  # Imprime: Rex
print(perro2.edad)    # Imprime: 5

# Visualización del proceso:
Clase: Plantilla o modelo de un perro, con atributos como nombre, edad, raza, y métodos como ladrar y comer.


Instancia: Un perro real, como "Rex" o "Bella", que tiene sus propios valores para estos atributos y puede ejecutar los métodos definidos en la clase.


Métodos: Acciones o comportamientos que el perro puede realizar, como ladrar o comer.


Atributos: Son las características o propiedades del perro, como su nombre, edad y raza.

In [ ]:
# Definir la clase Perro
class Perro:
    def __init__(self, nombre, edad, raza):
        self.nombre = nombre  # Atributo
        self.edad = edad
        self.raza = raza

    # Método ladrar
    def ladrar(self):
        print(f"{self.nombre} está ladrando!")

    # Método comer
    def comer(self, comida):
        print(f"{self.nombre} está comiendo {comida}.")

# Crear instancias (objetos) de la clase Perro
perro1 = Perro("Rex", 3, "Labrador")
perro2 = Perro("Bella", 5, "Beagle")

# Acceder a atributos
print(perro1.nombre)  # Imprime: Rex
print(perro2.edad)    # Imprime: 5

# Usar los métodos
perro1.ladrar()  # Imprime: Rex está ladrando!
perro2.comer("carne")  # Imprime: Bella está comiendo carne.

### Resumen:
Clase: Define el plano o la plantilla para los objetos.

Instancia: Un objeto concreto creado a partir de la clase.

Atributos: Las características del objeto (nombre, edad, etc.).

Métodos: Las acciones que el objeto puede realizar (ladrar, comer, etc.).

Este enfoque de programación te permite organizar y estructurar mejor tu código, encapsulando los datos y comportamientos relacionados en "objetos" que pueden interactuar entre sí.